// <auto-generated />
namespace Dialog.DataBase.Migrations.DialogMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MessagesList_UserRefAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessagesList_UserRefAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201703131515055_MessagesList_UserRefAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
