// <auto-generated />
namespace Dialog.DataBase.Migrations.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropAspTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropAspTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151140114_DropAspTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
